In [1]:
# Import libraries

# Load libraries
import pandas
import numpy
import numpy as np
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from scipy.stats import truncnorm
from sklearn.model_selection import GridSearchCV

import seaborn as sns

# Load Dataset

readdata = pandas.read_csv('Data11tumors.csv')
dataset = pandas.DataFrame(readdata)

# Apllying Exploratory Data Analysis

# Summarize the Dataset

# shape
print(dataset.shape)

# head
print(dataset.head(20))

# Statistical Summary

# descriptions
print(dataset.describe())

# class distribution
print(dataset.groupby('Classes').size())

correct_labels = dataset['Classes'].values

(174, 12534)
    Classes  Gen1  Gen2  Gen3  Gen4  Gen5  Gen6  Gen7  Gen8  Gen9  ...  \
0         7   153   228    32    30   -36    48   984   -19   537  ...   
1         7   154    99    43    55    66    63  5051   -26  1001  ...   
2         7    84    85    19    28  -104    28  2387   -80  1131  ...   
3         7   234   169    40    36    81     6  2657    -6  1214  ...   
4         7   104    58    42    13   107     5  3562    18  1464  ...   
5         7   207   408    56     6    41    33  2617    40  1243  ...   
6         7   188   245    45    18   -15    44  1885    25  1313  ...   
7         7   221   132    84    19    81    74  2589   -21   742  ...   
8         7   198   328    13    41    16    38  2536   -35  1006  ...   
9         7   303   261    53    71   -40    66  1184   -28   711  ...   
10        1   247   348    65    89    28     6    27   -54  1857  ...   
11        1   173   380    54    87   -11   -27   750    -9  1458  ...   
12        1   135   321  

In [2]:
feature_vectors = dataset.drop(['Classes'], axis=1)
feature_vectors

Gen1  Gen2  Gen3  Gen4  Gen5  Gen6  Gen7  Gen8  Gen9  Gen10  ...  \
0     153   228    32    30   -36    48   984   -19   537   1886  ...   
1     154    99    43    55    66    63  5051   -26  1001   1315  ...   
2      84    85    19    28  -104    28  2387   -80  1131   2457  ...   
3     234   169    40    36    81     6  2657    -6  1214   1944  ...   
4     104    58    42    13   107     5  3562    18  1464   1385  ...   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...   
169   157   578    40    58     5   -49    57   -29  3306    707  ...   
170   286   882   110   -19  -142   -66    -5    23  2701   1360  ...   
171   579   667    55   -41   -98  -138  -164   -61  2812   5167  ...   
172   252   582    88     3    44  -162   553  -150  2020   6945  ...   
173    83   420    14    84    12     1   153   -38  1833   1324  ...   

     Gen12524  Gen12525  Gen12526  Gen12527  Gen12528  Gen12529  Gen12530  \
0         100        30        83        28        57       106       128   
1          27        43        90        30        82       485       896   
2         -32        51       110        10        86        62        76   
3          43        52        82        12       135        60        69   
4         159        42        73         1        82        60        50   
..        ...       ...       ...       ...       ...       ...       ...   
169         4        45        64        37       169        91       180   
170       -91       130       137       -61        75        36        58   
171      -110       107       199       -60        59         8        77   
172       -66        92       -26       -44       148        43        73   
173        -5        85        96        92        67        32        30   

     Gen12531  Gen12532  Gen12533  
0           5        74      -188  
1          -2        91       -78  
2         -47        92      -103  
3          22        89      -180  
4          30        74      -198  
..        ...       ...       ...  
169        -4        60      -142  
170        44       161      -433  
171       -42       171      -371  
172         0       201      -333  
173        12        80      -180  

[174 rows x 12533 columns]

In [3]:
# Applying the Machine Learning algorithm Gaussian Naïve Bayes

from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(feature_vectors)
scaled_features = scaler.transform(feature_vectors)


# Split-out validation dataset
#from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(scaled_features, correct_labels, test_size=0.2, random_state=0)

In [4]:
# Make predictions on validation dataset

GB = GaussianNB()
GB.fit(X_train, y_train)
predictions = GB.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.8857142857142857
[[2 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0]
 [0 0 0 0 4 0 0 1 0]
 [0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 2 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           2       0.67      1.00      0.80         4
           3       0.83      1.00      0.91         5
           4       1.00      0.50      0.67         2
           5       1.00      0.80      0.89         5
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         7
           9       0.50      0.33      0.40         3
          10       1.00      1.00      1.00         5

    accuracy                           0.89        35
   macro avg       0.89      0.85      0.85        35
weighted avg       0.90      0.89      0.88        35



In [5]:
# Evaluating the performance with parameters optimization

param_grid_nb = {
    'var_smoothing': np.logspace(0,-9, num=100)
}


In [6]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
nbModel_grid = GridSearchCV(estimator=GaussianNB(), param_grid=param_grid_nb, verbose=1, cv=5, n_jobs=-1)
nbModel_grid.fit(X_train, y_train)
print(nbModel_grid.best_estimator_)

#Fitting 5 folds for each of 100 candidates, totalling 500 fits
GaussianNB(priors=None, var_smoothing=1.0)

Fitting 5 folds for each of 100 candidates, totalling 500 fits
GaussianNB(var_smoothing=0.005336699231206307)


GaussianNB(var_smoothing=1.0)

In [7]:
y_pred = nbModel_grid.predict(X_test)
print(y_pred)

[ 5  7  6  5  3 10  7  7  9  2  2  2  7 10  0 10  3  2  5  4  6  3  7  3
  2  2  3  7 10  0  2  5 10  3  7]


In [8]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred), ": is the confusion matrix")
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred), ": is the accuracy score")
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred), ": is the classification report")


[[2 0 0 0 0 0 0 0 0]
 [0 4 0 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0]
 [0 1 0 0 4 0 0 0 0]
 [0 0 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 2 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 5]] : is the confusion matrix
0.8857142857142857 : is the accuracy score
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           2       0.57      1.00      0.73         4
           3       0.83      1.00      0.91         5
           4       1.00      0.50      0.67         2
           5       1.00      0.80      0.89         5
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         7
           9       1.00      0.33      0.50         3
          10       1.00      1.00      1.00         5

    accuracy                           0.89        35
   macro avg       0.93      0.85      0.85        35
weighted avg       0.93      0.89      0.88        35
 : is the classification report
